#!/bin/bash -ex
# executed after apply-overlay

apt-get update

apt-get -y install adduser             
apt-get -y install postgresql-client   
apt-get -y install python              

echo "------------------------"
echo " InstallNeeded Packages "
echo "---------- -------------"
apt-get -y install python-psycopg2
apt-get -y install python-lxml
apt-get -y install python-tz
apt-get -y install python-yaml
apt-get -y install python-reportlab
apt-get -y install python-mako
apt-get -y install python-pychart
apt-get -y install python-werkzeug
apt-get -y install python-pybabel
apt-get -y install python-dateutil
apt-get -y install python-openid
apt-get -y install python-imaging
apt-get -y install python-psutil
apt-get -y install python-docutils
apt-get -y install python-unittest2
apt-get -y install python-mock
apt-get -y install python-jinja2
apt-get -y install python-pypdf
apt-get -y install python-passlib
apt-get -y install python-requests
apt-get -y install python-decorator

wget http://gdata-python-client.googlecode.com/files/gdata-2.0.17.tar.gz
tar -zxvf gdata-2.0.17.tar.gz
cd gdata-2.0.17
python setup.py install
cd ..

apt-get -y install python-feedparser   /* universal Feed Parser for Python */
apt-get -y install python-ldap         /* LDAP interface module */
apt-get -y install python-libxslt1     /* python bindings for XSLT transformation library */
apt-get -y install python-pydot        /* provides a full interface to create, handle, modify and process graphs in Graphvizs dot language. */
apt-get -y install python-pyparsing    /* library for parsing Python code */
apt-get -y install python-simplejson   /* simple, fast, extensible JSON encoder/decoder */
apt-get -y install python-vatnumber    /* module to validate VAT numbers for European countries */
apt-get -y install python-vobject      /* VObject simplifies the process of parsing and creating iCalendar and vCard objects. */
apt-get -y install python-xlwt         /* module for reading/writing Microsoft Excel spreadsheet files */
apt-get -y install python-gevent       /* gevent is a coroutine-based Python networking library */
apt-get -y install wkhtmltopdf         /* Command line utilities to convert html to pdf or image using WebKit  */
apt-get -y install python-gdata        /* Google Data Python client library */
apt-get -y install python-pip          /* Needed to install psycogreen */

apt-get -y install xfonts-base         /* Needed for upstream wkhtmltox package */
apt-get -y install xfonts-75dpi        /* Needed for upstream wkhtmltox package */

# echo "------------------------"
# echo " Make SSL work properly "
# echo "------------------------"
# #a2enmod ssl proxy_http headers rewrite
# #service apache2 restart
# #a2ensite openerp-ssl
# #/etc/init.d/apache2 restart

# # Enable needed modules
# a2enmod proxy_http headers rewrite		

# # Configure sites
# a2dissite 000-default
# a2ensite odoo.conf
# service apache2 reload
