#!/bin/bash -ex
# executed after apply-overlay

apt-get update

apt-get -y install adduser             
apt-get -y install postgresql-client   
apt-get -y install python              

echo "------------------------"
echo " InstallNeeded Packages "
echo "---------- -------------"
apt-get -y install python-psycopg2
apt-get -y install python-lxml
apt-get -y install python-tz
apt-get -y install python-yaml
apt-get -y install python-reportlab
apt-get -y install python-mako
apt-get -y install python-pychart
apt-get -y install python-werkzeug
apt-get -y install python-pybabel
apt-get -y install python-dateutil
apt-get -y install python-openid
apt-get -y install python-imaging
apt-get -y install python-psutil
apt-get -y install python-docutils
apt-get -y install python-unittest2
apt-get -y install python-mock
apt-get -y install python-jinja2
apt-get -y install python-pypdf
apt-get -y install python-passlib
apt-get -y install python-requests
apt-get -y install python-decorator

wget http://gdata-python-client.googlecode.com/files/gdata-2.0.17.tar.gz
tar -zxvf gdata-2.0.17.tar.gz
cd gdata-2.0.17
python setup.py install
cd ..

apt-get -y install python-feedparser
apt-get -y install python-ldap 
apt-get -y install python-libxslt1
apt-get -y install python-pydot
apt-get -y install python-pyparsing
apt-get -y install python-simplejson
apt-get -y install python-vatnumber
apt-get -y install python-vobject
apt-get -y install python-xlwt
apt-get -y install python-gevent
apt-get -y install wkhtmltopdf
apt-get -y install python-gdata
apt-get -y install python-pip

apt-get -y install xfonts-base
apt-get -y install xfonts-75dpi
